# Generated by Django 2.1.5 on 2019-01-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(blank=True, max_length=1000, null=True)),
                ('lastname', models.TextField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=1000, null=True)),
                ('password', models.TextField(blank=True, max_length=1000, null=True)),
                ('country', models.TextField(blank=True, choices=[('US', 'United States'), ('BR', 'Brazil')], max_length=1000, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=100, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('emailCreate', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
