# Generated by Django 2.1.5 on 2019-01-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sign_up', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='emailCreate',
            new_name='emailCreated',
        ),
    ]
