# Generated by Django 2.1.5 on 2019-01-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sign_up', '0002_auto_20190130_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ngCreated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
