# Generated by Django 2.1.5 on 2019-01-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sign_up', '0003_person_ngcreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
